server:
  port: 2020

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/motorecord?serverTimezone=GMT%2B8
    username: motorecord
    password: motorecord
